config/routes.rb
Rails.application.routes.draw do


  get 'homes/top'
  get '/home/about', to: 'homes#about'
  root to: 'homes#top'
  devise_for :users
  resources :books
  resources :users, only: [:index, :create, :show, :edit, :update]
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  # attr_accessor :name, :introduction

  validates :name, uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20, too_short: "is too short (minimum is 2 characters)", too_long: "is too long (maximum is 20 characters)" }
  validates :introduction, length: { maximum: 50, too_long: "is too long (maximum is 50 characters)" }

  def get_profile_image(width, height)
    unless  profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end



  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>Editing Book</h2>
              <% if @book.errors.any? %>
              <strong>
                <%= @book.errors.count %> errors prohibited this obj from being saved:
              </strong>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
              <% end %>

            <%= form_with model: @book do |f| %>
              <div class="form-group">
                <label for="book_title">Title</label>
                <input class="form-control book_title" type="text" name="book[title]" id="book_title", value="<%= @book.title %>">
              </div>

              <div class="form-group">
                <label for="book_body">Opinion</label>
                <textarea class="form-control book_body" name="book[body]" id="book_body"><%= @book.body %></textarea>
              </div>

              <div class="form-group">
                <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
              </div>
            <% end %>

            <%= link_to "Show", book_path %>
            |
            <%= link_to "Back", books_path %>
        </div>
      </div>
    </div>

app/views/books/index.html.erb
<p id="notice"></p>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
                <%= render 'users/list', book: @book, user: @user %>
            </div>

            <div class="col-md-8 offset-md-1">
                <h1>Books</h1>
                    <table class="table table-hover table-inverse">
                        <thead>
                            <tr>
                                <th colspn="1"></th>
                                <th>Title</th>
                                <th>Opinion</th>
                            </tr>
                        </thead>

                        <tbody>
                            <% @books.each do |book| %>
                                <tr>
                                    <td>
                                        <%= link_to user_path(book.user.id) do %>
                                            <%= image_tag book.user.get_profile_image(100,100) %>
                                        <% end %>
                                    </td>
                                    <td><%= link_to book.title, book_path(book.id) %></td>
                                    <td><%= book.body %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
        </div>
    </div>

app/views/books/show.html.erb
<p id="notice"></p>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
              <%= render 'users/list', book: @book, user: @user %>
            </div>
            <div class="col-md-8 offset-md-1">
              <h1>Book detail</h1>
                <table class="table table-hover table-inverse">
                  <tr>
                    <td rowspan="3">
                      <%= link_to user_path(@user.id) do %>
                        <%= image_tag @user.get_profile_image(100,100) %> <br>
                        <%= @user.name %>
                      <% end %>
                    </td>
                    <td><%= link_to @book.title, book_path(@book.id) %></td>
                    <td><%= @book.body %></td>
                    <% if @book.user == current_user %>
                      <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
                      <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %></td>
                    <% end %>
                  </tr>
                </table>
            </div>
       </div>
   </div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auot">
      Welcome to
      <i class="fa-solid fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
    <div class="container">
        <div class="row">
            <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                <h1>
                       welcome to
                    <i class="fa-solid fa-book"></i>Bookers
                    !!
                </h1>
                <p>In <i class="fa-solid fa-book"></i>Bookers,<br>
                    you can share and exchange your opinions , inpressions , and emotions<br>
                    about various books!<br>
                <div class="btn-wrapper col-10 mx-auto">
                    <div class="row">
                      <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
                    </div>
                    <div class="row">
                        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                    </div>
                    <div class="row">
                        <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/a335047646.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

              <li class="nav-item">
                <%=link_to  user_path(current_user), class: "nav-link text-light" do %>
                  <i class="fa-solid fa-house text-white"></i>
                  Home
                <% end %>
              </li>
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-users text-white"></i>
                  Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-book-open text-white"></i>
                  Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do  %>
                  <i class="fa-solid fa-right-from-bracket text-white"></i>
                  Log out
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-house text-white"></i>
                  Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to '/home/about', class: "nav-link text-light" do %>
                  <i class="fa-solid fa-link text-white"></i>
                  About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to '/users/sign_up', class: "nav-link text-light" do %>
                  <i class="fa-solid fa-user-plus text-white"></i>
                  Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to '/users/sign_in', class: "nav-link text-light" do %>
                  <i class="fa-solid fa-right-to-bracket text-white"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: message_type %>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<% if book.errors.any? %>
<strong>
    <%= book.errors.count %> errors prohibited this obj from being saved:
</strong>
    <ul>
        <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<h1>User info</h1>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
        <tbody>
            <tr>
               <th>name</th>
                <th><%= user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <% unless user.guest_user? %>
      <div class="row">
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
    <% end %>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: Book.new, url: books_path, method: :post do |f| %>
        <div class="form-group">
            <label for="book_title">Title</label>
            <input class="form-control book_title" type="text" name="book[title]" id="book_title">
        </div>

        <div class="form-group">
            <label for="book body">Opinion</label>
            <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
        </div>

        <div class="form-group">
            <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
        </div>
    <% end %>

app/views/users/edit.html.erb
<p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>
            <% if @user.errors.any? %>
              <strong>
                <%= @user.errors.count %> errors prohibited this obj from being saved:
              </strong>
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
            <% end %>
                </ul>
              <% end %>

            <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>

              <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control name" type="text" name="user[name]" id="user_name", value="<%= @user.name %>">
              </div>

              <div class="form-group">
                <label for="image">Image</label>
                <p><%= f.file_field :profile_image, placeholder: "画像", accept: "image/*" %></p>
              </div>

              <div class="form-group">
                <label for="user_introduction">Introduction</label>
                <textarea class="form-control user_introduction" name="user[introduction]" id="user_introduction"><%= @user.introduction %></textarea>
              </div>

              <p><%= f.submit "Update User", class: "btn btn-secondary" %></p>

            <% end %>
        </div>
      </div>
    </div>

app/views/users/index.html.erb
<p id="notice"></p>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <%= render 'list', book: @book, user: @user %>
            </div>

            <div class="col-md-8 offset-md-1">
                <h1>Users</h1>
                    <table class="table table-hover table-inverse">
                        <thead>
                            <tr>
                                <th>image</th>
                                <th>name</th>
                                <th colspan="1"></th>
                            </tr>
                        </thead>

                        <tboby>
                            <% @users.each do |user| %>
                                <tr>
                                    <td><%= image_tag user.get_profile_image(100,100) %></td>
                                    <td><%= user.name %></td>
                                    <td><%= link_to "Show", user_path(user.id) %></td>
                                </tr>
                            <% end %>
                        </tboby>
                    </table>
            </div>
        </div>
    </div>

app/views/users/show.html.erb
<p id="notice"></p>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
                <%= render 'list', book: @book, user: @user %>
            </div>

            <div class="col-md-8 offset-md-1">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspn="3"></th>
                        </tr>
                    </thead>

                    <tbody>
                    <% @books.each do |book| %>
                        <tr>
                            <td><%= link_to user_path(book.user.id) do %>
                                    <%= image_tag book.user.get_profile_image(100,100) %>
                                <% end %>
                            </td>
                            <td><%= link_to book.title, book_path(book.id) %></td>
                            <td><%= book.body %></td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>